examples/issue227.dhall, examples/issue227.ipso, ipso-eval/src/closure_conversion/mod.rs, ipso-eval/src/closure_conversion/test.rs
=> fix(eval)!: fix closure conversion for let bindings

examples/environmentVariables.dhall, examples/environmentVariables.ipso, examples/programArgs.dhall, examples/programArgs.ipso, ipso-builtins/src/env.rs, ipso-builtins/src/lib.rs, ipso-core/src/lib.rs, ipso-eval/src/lib.rs
=> Implement `env` module

examples/exitFailure.dhall, examples/exitFailure.ipso, examples/exitSuccess.dhall, examples/exitSuccess.ipso, examples/exitWith.dhall, examples/exitWith.ipso, ipso-builtins/src/exit.rs, ipso-builtins/src/lib.rs, ipso-core/src/lib.rs, ipso-eval/src/lib.rs
=> feat: add `exit` module

docs/reference.html, site/pages/docs/reference.md
=> docs: add exit module

ipso-builtins/src/file.rs, ipso-builtins/src/lib.rs, ipso-core/src/lib.rs, ipso-eval/src/lib.rs
=> feat: add file module

.github/workflows/checkReleaseVersion, .github/workflows/ipso-cli.yml, ipso-cli/src/lib.rs, ipso-cli/src/main.rs, ipso-cli/src/repl/mod.rs, ipso-cli/src/version.rs
=> Display version in `ipso-cli`

examples/negation.dhall, examples/negation.ipso, ipso-core/src/lib.rs, ipso-eval/src/closure_conversion/mod.rs, ipso-eval/src/lib.rs, ipso-lex/src/lib.rs, ipso-lex/src/test.rs, ipso-lex/src/token/mod.rs, ipso-parse/src/lib.rs, ipso-syntax/src/lib.rs, ipso-typecheck/src/declaration/mod.rs, ipso-typecheck/src/module/mod.rs, ipso-typecheck/src/type_inference/mod.rs
I'm a little embarrassed that I forgot to implement this!
=> Signed `Int`s

examples/arrayEach.dhall, examples/arrayEach.ipso, examples/cmdEachline.dhall, examples/cmdEachline.ipso, ipso-builtins/src/array.rs, ipso-builtins/src/cmd.rs, ipso-core/src/lib.rs, ipso-eval/src/lib.rs
=> Add `array.each_` and `cmd.eachline_`

examples/duplicateTopLevelDefs.dhall, examples/duplicateTopLevelDefs.ipso, examples/issue144.dhall, ipso-builtins/src/array.rs, ipso-builtins/src/char.rs, ipso-builtins/src/cmd.rs, ipso-builtins/src/env.rs, ipso-builtins/src/exit.rs, ipso-builtins/src/file.rs, ipso-builtins/src/int.rs, ipso-builtins/src/io.rs, ipso-builtins/src/lib.rs, ipso-builtins/src/path.rs, ipso-builtins/src/string.rs, ipso-cli/src/run.rs, ipso-core/src/lib.rs, ipso-diagnostic/src/lib.rs, ipso-eval/src/lib.rs, ipso-import/src/lib.rs, ipso-parse/src/grammar/module/mod.rs, ipso-parse/src/grammar/module/test.rs, ipso-syntax/src/lib.rs, ipso-typecheck/src/declaration/mod.rs, ipso-typecheck/src/lib.rs, ipso-typecheck/src/test.rs
=> Disallow duplicate top-level definitions

Cargo.lock, Cargo.nix, examples/issue215.dhall, examples/issue215.ipso, ipso-core/src/lib.rs, ipso-eval/src/closure_conversion/mod.rs, ipso-eval/src/lib.rs, ipso-import/src/lib.rs, ipso-lex/Cargo.toml, ipso-lex/src/lib.rs, ipso-lex/src/test.rs, ipso-lex/src/token/mod.rs, ipso-parse/src/grammar/expr/mod.rs, ipso-parse/src/lib.rs, ipso-syntax/src/desugar.rs, ipso-syntax/src/lib.rs, ipso-typecheck/src/type_inference/mod.rs
=> Use spaces to split up command parts

examples/issue216-cmd.dhall, examples/issue216-cmd.ipso, examples/issue216-string.dhall, examples/issue216-string.ipso, ipso-lex/src/lib.rs, ipso-lex/src/token/mod.rs
=> Disallow newline character in command and string literals

examples/2.dhall, examples/instance_parse_error.dhall, examples/issue188.dhall, examples/issue188.ipso, ipso-lex/src/lib.rs, ipso-lex/src/token/mod.rs, ipso-parse/src/grammar/expr/mod.rs, ipso-parse/src/grammar/expr/test.rs, ipso-parse/src/grammar/module/mod.rs, ipso-parse/src/grammar/module/test.rs, ipso-parse/src/lib.rs
=> Strip comments in lexer

examples/issue19.dhall, examples/issue19.ipso, ipso-typecheck/src/declaration/mod.rs, ipso-typecheck/src/evidence/mod.rs
=> Allow recursive type class instances

Cargo.lock, examples/issue218.dhall, examples/issue218.ipso, ipso-typecheck/Cargo.toml, ipso-typecheck/src/declaration/mod.rs, ipso-typecheck/src/metavariables.rs, ipso-typecheck/src/test.rs, ipso-typecheck/src/type_inference/mod.rs, ipso-typecheck/src/type_inference/test.rs, ipso-typecheck/src/type_inference/unification/mod.rs
=> Propagate known type information when checking

examples/cmdInterpolation3.dhall, examples/cmdInterpolation3.ipso, examples/issue216-cmd.dhall, ipso-lex/src/lib.rs, ipso-parse/src/grammar/expr/mod.rs
=> Expression interpolation in command literals

examples/issue273.dhall, examples/issue273.ipso, ipso-typecheck/src/type_inference/mod.rs
=> Fix incorrect pattern match type error location

.github/workflows/checkReleaseVersion, examples/splitString1.dhall, examples/splitString1.ipso, examples/splitString2.dhall, examples/splitString2.ipso, examples/todolist.ipso, ipso-builtins/src/string.rs, ipso-core/src/lib.rs, ipso-eval/src/lib.rs
=> `string.split : String -> String -> Array` and `string.splitc : Char -> String -> Array String`

docs/docs/reference.html, site/pages/docs/reference.md
=> docs: add string.split and string.splitc

docs/docs/reference.html, site/pages/docs/reference.md
=> docs: explain indentation rules

examples/debug.dhall, examples/debug.ipso, ipso-builtins/src/lib.rs, ipso-core/src/lib.rs, ipso-eval/src/lib.rs
=> `instance Debug Cmd`

.github/workflows/checkReleaseVersion, examples/stringParts.dhall, examples/stringParts.ipso, examples/todolist.ipso, ipso-builtins/src/string.rs, ipso-core/src/lib.rs, ipso-eval/src/lib.rs
=> `string.parts` and `string.partsc`

.github/workflows/tests.yml, .github/workflows/uploadToCache, .github/workflows/uploadToCacheMacos
=> build: translate uploadToCache[Macos] to ipso

docs/docs/reference.html, site/pages/docs/reference.md
=> docs: add `env.program` and `env.args`

.github/workflows/tests.yml, examples/issue300.dhall, examples/issue300.ipso, ipso-typecheck/src/test.rs, ipso-typecheck/src/type_inference/mod.rs
=> Calculate correct record field offsets

docs/docs/reference.html, site/pages/docs/reference.md
=> Nested patterns

docs/docs/reference.html, site/pages/docs/reference.md
=> docs: add unit patterns

examples/unitPattern1.dhall, examples/unitPattern1.ipso, examples/unitPattern2.dhall, examples/unitPattern2.ipso, ipso-core/src/lib.rs, ipso-eval/src/closure_conversion/mod.rs, ipso-eval/src/lib.rs, ipso-parse/src/grammar/pattern/mod.rs, ipso-syntax/src/desugar/mod.rs, ipso-syntax/src/lib.rs, ipso-typecheck/src/declaration/mod.rs, ipso-typecheck/src/type_inference/mod.rs
=> Unit patterns

Cargo.lock, Cargo.nix, ipso-cli/Cargo.toml, ipso-cli/src/main.rs
=> feat!: make -- signal end of options

.github/workflows/tests.yml
=> build: cache crates.io index

examples/not.dhall, examples/not.ipso, ipso-builtins/src/lib.rs
=> Implement `not : Bool -> Bool`

ipso-cli/src/lib.rs, ipso-cli/src/run.rs
=> feat(cli): add --check flag

examples/identifierBangAndQuestionMark.dhall, examples/identifierBangAndQuestionMark.ipso, ipso-lex/src/lib.rs
=> Allow ! and ? in identifiers

examples/getvarBang.dhall, examples/getvarBang.ipso, examples/getvarBangSuccess.dhall, examples/getvarBangSuccess.ipso, ipso-builtins/src/env.rs, ipso-cli/src/repl/mod.rs, ipso-cli/src/run.rs, ipso-core/src/lib.rs, ipso-eval/src/lib.rs, ipso-eval/src/test.rs, ipso-repl/src/lib.rs
=> Add env.getvar!

examples/trim.dhall, examples/trim.ipso, examples/trimc.dhall, examples/trimc.ipso, examples/trimp.dhall, examples/trimp.ipso, ipso-builtins/src/string.rs, ipso-core/src/lib.rs, ipso-eval/src/lib.rs
=> Whitespace stripping functions

examples/issue355.dhall, examples/issue355.ipso, ipso-lex/src/lib.rs
=> Allow escaped dollar signs in command literals

examples/try.dhall, examples/try.ipso, ipso-builtins/src/cmd.rs, ipso-core/src/lib.rs, ipso-eval/src/lib.rs
=> Add `cmd.try`

.github/workflows/tests.yml
=> build: run tests on pushes to main

examples/__skip.dhall, examples/issue138.dhall, examples/issue138.ipso, ipso-core/src/lib.rs, ipso-eval/src/closure_conversion/mod.rs, ipso-eval/src/lib.rs, ipso-import/src/lib.rs, ipso-parse/src/grammar/expr/mod.rs, ipso-syntax/src/desugar/mod.rs, ipso-syntax/src/lib.rs, ipso-typecheck/src/type_inference/mod.rs
Closes #138 
I intend to follow up with https://github.com/LightAndLight/ipso/issues/346
=> Quote-aware substitution in command literals

docs/docs/reference.html, site/pages/docs/reference.md
=> docs: rework command interpolation

examples/__skip.dhall, examples/cmdInterpolation2.ipso, examples/cmdInterpolation3.ipso, ipso-core/src/lib.rs, ipso-eval/src/closure_conversion/mod.rs, ipso-eval/src/lib.rs, ipso-import/src/lib.rs, ipso-lex/src/lib.rs, ipso-lex/src/test.rs, ipso-lex/src/token/mod.rs, ipso-parse/src/grammar/expr/mod.rs, ipso-parse/src/lib.rs, ipso-repl/src/lib.rs, ipso-syntax/src/desugar/mod.rs, ipso-syntax/src/lib.rs, ipso-typecheck/src/type_inference/mod.rs
=> Command argument splatting

docs/docs/reference.html, site/pages/docs/reference.md
=> docs: remove ToArgs class

examples/arrayPatterns.dhall, examples/arrayPatterns.ipso, examples/arrayPatternsError.dhall, examples/arrayPatternsError.ipso, ipso-core/src/lib.rs, ipso-eval/src/closure_conversion/mod.rs, ipso-eval/src/lib.rs, ipso-parse/src/grammar/pattern/mod.rs, ipso-syntax/src/desugar/mod.rs, ipso-syntax/src/lib.rs, ipso-typecheck/src/declaration/mod.rs, ipso-typecheck/src/type_inference/mod.rs, ipso-typecheck/src/type_inference/test.rs
=> Array pattern matching

examples/issue357.dhall, examples/issue357.ipso, ipso-core/src/lib.rs, ipso-syntax/src/lib.rs, ipso-typecheck/src/type_inference/mod.rs
=> Fix lambda pattern elaboration

examples/issue362.dhall, examples/issue362.ipso, ipso-eval/src/lib.rs
=> Fix variable scope in evaluator

examples/issue356.dhall, examples/issue356.ipso, ipso-parse/src/grammar/pattern/mod.rs
=> Allow empty string patterns

examples/issue359.dhall, examples/issue359.ipso, ipso-eval/src/lib.rs
=> Exit program when `string.parts` is called with an empty delimiter

examples/arrayPatternsError.dhall, examples/definitionArgTypeError.dhall, examples/definitionArgTypeError.ipso, examples/issue358.dhall, examples/issue358.ipso, ipso-syntax/src/desugar/mod.rs, ipso-typecheck/src/declaration/mod.rs, ipso-typecheck/src/test.rs, ipso-typecheck/src/type_inference/mod.rs, ipso-typecheck/src/type_inference/test.rs
=> Desugar nested patterns in lambda arguments and function definitions

ipso-builtins/src/array.rs, ipso-eval/src/bindings.rs, ipso-eval/src/lib.rs, ipso-eval/src/test.rs
Closes #189. See the issue for an explanation.
=> Fix `This` references in submodules

examples/25.dhall, examples/commentsErrors.ipso, examples/comp_expr_error_2.dhall, examples/etaReductionTypeError.dhall, examples/etaReductionTypeError.ipso, examples/issue377.dhall, examples/issue377.ipso, ipso-typecheck/src/type_inference/mod.rs
=> More localised errors in function applications

examples/issue365-2.dhall, examples/issue365-2.ipso, examples/issue365-3.dhall, examples/issue365-3.ipso, examples/issue365-4.dhall, examples/issue365-4.ipso, examples/issue365-5.dhall, examples/issue365-5.ipso, examples/issue365-6.dhall, examples/issue365-6.ipso, examples/issue365-7.dhall, examples/issue365-7.ipso, examples/issue365.dhall, examples/issue365.ipso, ipso-parse/src/grammar/type/mod.rs
=> Loosen indentation rules for record and variant types

ipso-core/src/lib.rs, ipso-syntax/src/kind.rs, ipso-typecheck/src/type_inference/mod.rs, ipso-typecheck/src/type_inference/unification/mod.rs
=> refactor: reduce allocations when typechecking App nodes

examples/issue395.dhall, examples/issue395.ipso, ipso-lex/src/lib.rs
=> Allow literal backslashes in strings

examples/toCharsFromChars.dhall, examples/toCharsFromChars.ipso, ipso-builtins/src/string.rs, ipso-core/src/lib.rs, ipso-eval/src/lib.rs
=> feat: add string.toChars and string.fromChars

examples/startsWith.dhall, examples/startsWith.ipso, examples/stripPrefix.dhall, examples/stripPrefix.ipso, ipso-builtins/src/string.rs, ipso-core/src/lib.rs, ipso-eval/src/lib.rs
=> feat: add string.stripPrefix and string.startsWith

examples/filter.dhall, examples/filter.ipso, ipso-builtins/src/array.rs, ipso-core/src/lib.rs, ipso-eval/src/lib.rs
=> feat: add array.filter and array.filterMap

examples/find.dhall, examples/find.ipso, ipso-builtins/src/array.rs, ipso-core/src/lib.rs, ipso-eval/src/lib.rs, ipso-eval/src/reflect.rs
=> Implement array.find and array.findMap

.github/workflows/ipso-cli.yml, .github/workflows/postBuildHook, .github/workflows/postBuildHookMacos, .github/workflows/tests.yml, .github/workflows/uploadToCacheMacos, ipso-cli/src/version.rs
See https://github.com/LightAndLight/ipso/issues/407
=> Try to fix Nix binary caching

.github/workflows/ipso-cli.yml, .github/workflows/postBuildHookMacos, .github/workflows/tests.yml
Part of https://github.com/LightAndLight/ipso/issues/407
=> Fix MacOS post build hook

examples/morePrintlns.dhall, examples/morePrintlns.ipso, flake.nix, ipso-builtins/src/lib.rs, ipso-core/src/lib.rs, ipso-eval/src/lib.rs
=> Add eprintln and dprintln

Cargo.lock, Cargo.nix, examples/intParse.dhall, examples/intParse.ipso, ipso-builtins/src/int.rs, ipso-core/src/lib.rs, ipso-eval/Cargo.toml, ipso-eval/src/lib.rs
=> Add `int.parse{Bin,Dec,Oct,Hex}`

examples/minMax.dhall, examples/minMax.ipso, ipso-builtins/src/int.rs, ipso-core/src/lib.rs, ipso-eval/src/lib.rs
=> Add `int.min` and `int.max`

.github/workflows/uploadToCache, .github/workflows/uploadToCacheMacos, examples/todolist.ipso
Uses new features in the various Ipso code I have lying around.
=> Update Ipso code

docs/docs/reference.html, site/pages/docs/reference.md
=> docs: add new builtins
